[tool.yapf]
based_on_style = "google"
indent_width = 2

[tool.yapfignore]
ignore_patterns = [
  '**/node_modules',
  '**/__pycache__',
  '**/_bazel',
  '**/bazel-out',
  '**/.git'
]

[tool.isort]
skip_gitignore = true
force_single_line = true
lexicographical = true
force_sort_within_sections = true
single_line_exclusions = ['typing']
known_first_party = [
  "labtools",
  "probing",
]

[tool.pyright]
exclude = [
  '**/node_modules',
  '**/__pycache__',
  '**/_bazel',
  '**/bazel-out',
]
ignore = [
  '**/*.gin'
]

reportMissingImports = false
reportMissingModuleSource = false
